# Generated by Django 5.0.3 on 2024-09-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atividade',
            new_name='Atividades',
        ),
    ]
