# Generated by Django 5.0.3 on 2024-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_funcionarios', '0002_rename_atividade_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividades',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
