# Generated by Django 5.0.3 on 2024-09-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_funcionarios', '0003_atividades_deletado_alter_atividades_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='deletado',
        ),
    ]
