# Generated by Django 5.1.1 on 2024-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_funcionarios', '0004_remove_atividades_deletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='categoria',
            field=models.CharField(choices=[('Nao Resolvido', 'Não Resolvido'), ('Em Progresso', 'Em Progresso'), ('Concluido', 'Concluído')], default='Nao Resolvido', max_length=20),
        ),
        migrations.AddField(
            model_name='atividades',
            name='regiao',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Nordeste', 'Nordeste'), ('Centro-Oeste', 'Centro-Oeste'), ('Sudeste', 'Sudeste'), ('Sul', 'Sul')], default='Norte', max_length=20),
        ),
    ]
