# Generated by Django 5.0.3 on 2024-09-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
